pur_beurre/catalog/urls.py
"""urls management"""
from django.urls import path
from . import views

app_name = "catalog"

urlpatterns = [
    path('', views.index, name='index'),
    path('credits/', views.credits, name='credits'),
    path('search/', views.search, name='search'),
    path('substitute/<str:product_id>/', views.detail, name='detail'),
    path('favorite/<str:product_id>/', views.favorite, name='favorite'),
]

pur_beurre/pur_beurre/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('content/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('login/', views.user_login, name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('favorite/', views.favorite, name='favorite'),
    path('password-change/', views.change_password, name="change_form"),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html'), name='password_reset'
         ),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'
         ),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'
         ),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'
         ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pur_beurre/catalog/models.py
"""model management"""
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    """Category table"""
    name = models.CharField(max_length=100)


class Product(models.Model):
    """Product table"""
    name = models.CharField(max_length=200, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="product")
    brand = models.CharField(max_length=200)
    nutrition_grade = models.CharField(max_length=1)
    picture = models.URLField()
    nutrition_image = models.URLField()
    url = models.URLField()
    last_modified_t = models.DateField(null=True, blank=True)
    openff_id = models.BigIntegerField(null=True, blank=True)


class UserFavorite(models.Model):
    """UserFavorite table"""
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

pur_beurre/users/forms.py
"""Forms management"""
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    """manages registration"""
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ConnexionForm(forms.Form):
    """manages the connection"""
    username = forms.CharField(label="Nom d'utilisateur", max_length=30)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)

pur_beurre/catalog/views.py
"""views management"""
import logging

from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages

from .models import Product, UserFavorite


# Create your views here.
def index(request):
    """index view"""
    template = loader.get_template('catalog/index.html')
    return HttpResponse(template.render(request=request))


def credits(request):
    """credits view"""
    return render(request, 'catalog/credits.html')


def search(request):
    """search view"""
    user_query = request.GET.get('query')
    query = str.capitalize(user_query)
    try:
        product = Product.objects.filter(name=query).first()
        substitutes = Product.objects.filter(
            category=product.category,
            nutrition_grade__lt=product.nutrition_grade).order_by(
                "nutrition_grade")
        paginator = Paginator(substitutes, 6)
        page = request.GET.get('page')
        alt_products = paginator.get_page(page)
        context = {
            'alt_products': alt_products,
            'paginate': True,
            'title': query,
            'image': product.picture,
        }
    except AttributeError:
        messages.warning(request, "Ce produit n'existe pas. Vérifiez l'orthographe de la recherche")
        return redirect('catalog:index')
    logging.info('New search', exc_info=True, extra={
        'request': request,
    })
    return render(request, 'catalog/search.html', context)


def detail(request, product_id):
    """detail view"""
    product = Product.objects.get(id=product_id)

    context = {
        'name': product.name,
        'title': 'Informations nutritionnelles',
        'product': product,
        'nutrition_image': product.nutrition_image,
    }

    return render(request, 'catalog/detail.html', context)


@login_required
def favorite(request, product_id):
    """favorite view"""
    try:
        UserFavorite.objects.get(user_name_id=request.user.id,
                                 product_id=(product_id)
                                 )
        messages.warning(request, 'Ce produit est déjà dans vos favoris.')
        return redirect(request.META.get('HTTP_REFERER'))
    except ObjectDoesNotExist:
        UserFavorite.objects.create(user_name_id=request.user.id,
                                    product_id=(product_id)
                                    )
        messages.success(request, 'Le produit a bien été enregistré.')
        return redirect(request.META.get('HTTP_REFERER'))

pur_beurre/users/views.py
"""Views management"""
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from catalog.models import Product
from .forms import RegisterForm, ConnexionForm


def register(request):
    """register view"""
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Votre compte a bien été crée')
            return redirect('catalog:index')
    else:
        form = RegisterForm()

    return render(request, 'users/register.html', {'form': form})


def user_login(request):
    """login view"""
    error = False
    if request.method == "POST":
        form = ConnexionForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)  # check if data is correct
            if user:  # if the returned object is not None
                login(request, user)  # connect the user
            else:  # otherwise an error will be displayed
                error = True
    else:
        form = ConnexionForm()

    return render(request, 'users/login.html', locals())


def user_logout(request):
    """logout view"""
    logout(request)
    return render(request, 'users/logout.html')


@login_required
def profile(request):
    """profile view"""
    return render(request, 'users/profile.html')


@login_required
def favorite(request):
    """favorite view"""
    user = request.user
    fav = Product.objects.filter(userfavorite__user_name=user.id)
    if fav:
        product = Product.objects.filter(pk__in=fav)
    else:
        product = []

    return render(request, 'users/favorite.html', {'favorite': product})


@login_required
def change_password(request):
    """Change password view"""
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Votre mot de passe a bien été modifié!')
            return redirect('catalog:index')
    else:
        form = PasswordChangeForm(user=request.user)

    return render(request, 'users/password_change_form.html', {'form': form})

pur_beurre/catalog/templates/catalog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Pur Beurre</title>

  <!-- Font Awesome Icons -->
  <link href="{% static 'catalog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Fonts -->
  <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">

  <!-- Plugin CSS -->
  <link href="{% static 'catalog/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'catalog/css/creatives.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'catalog/css/main.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <img id="logo" src="{% static 'catalog/img/pb1.png' %}" title="Pur Beurre" alt="Pur Beurre"/>
      <a class="navbar-brand js-scroll-trigger" href="/"><strong>Pur Beurre</strong></a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li>
            <form id="search-nav"  action="{% url 'catalog:search' %}" method="get" accept-charset="utf-8">
                <input type="text" name="query" id ="querynav" placeholder="Chercher un produit" required>
            </form>
          </li>

          {% if user.is_authenticated %}

          <li class="nav-item icon">
             <a href="{% url 'profile' %}"> <i class="fas fa-user fa-2x" data-toggle="tooltip" title="Mon Profile" ></i></a>
          </li>
          <li class="nav-item icon">
            <a href="{% url 'favorite' %}"> <i class="fas fa-carrot fa-2x" data-toggle="tooltip" title="Mes produits"></i></a>
          </li>
          <li class="nav-item icon">
            <a href="{% url 'logout' %}"> <i class="fas fa-sign-out-alt fa-2x" data-toggle="tooltip" title="Déconnexion" ></i></a>
          </li>

          {% else %}

          <li class="nav-item icon">
            <a href="{% url 'register' %}"> <i class="fas fa-user-plus fa-2x" data-toggle="tooltip" title="S'inscrire"></i></a>
          </li>
          <li class="nav-item icon">
            <a href="{% url 'login' %}"> <i class="fas fa-sign-in-alt fa-2x" data-toggle="tooltip" title="Se Connecter"></i></a>
          </li>

          {% endif %}

        </ul>
      </div>
    </div>
  </nav>

  {% block content %}{% endblock %}

    <!-- Contact Section -->
  <section class="page-section" id="contact">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="mt-0">Contactez-nous!</h2>
          <hr class="divider my-4">
          <p class="text-muted mb-5"><strong>Notre idée de Plateforme vous plait ? Vous désirez nous soutenir ou nous faire part d'un axe d'amélioration ? Vous trouverez ci-dessous nos coordonnées!</strong></p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
          <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
          <div>01.57.00.00.00</div>
        </div>
        <div class="col-lg-4 mr-auto text-center">
          <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
          <!-- Make sure to change the email address in anchor text AND the link below! -->
          <a class="d-block" href="mailto:contact@yourwebsite.com">contact@pur_beurre.com</a>
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
      <section class="bg-footer">
         <div class="container">
            <div class="row">
               <div class="col-lg-6 col-md-6 text-center">
                  <div class="service-box mt-5 mx-auto">
                     <i class="fas fa-4x fa-gem text-icone mb-3 sr-icon-1" ></i><br>
                     <a href ="{% url 'catalog:credits' %}" class="mb-3 a-headings">Mentions légales</a>
                     <p class="text-muted mb-0"><strong>Nos différentes sources.</strong></p>
                  </div>
               </div>
               <div class="col-lg-6 col-md-6 text-center">
                  <div class="service-box mt-5 mx-auto">
                     <i class="fas fa-4x fa-paper-plane text-icone mb-3 sr-icon-2"></i><br>
                     <a href="#contact" class="mb-3 a-headings js-scroll-trigger">Contact</a>
                     <p class="text-muted mb-0"><strong>Nous sommes a votre écoute !</strong></p>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-lg-12 col-md-6 text-center mt-5">
                  <h6 class="custom_title" style="font-family:'Scope One'"><br><strong>Mathieu Ferrandeau - Projet 8 Développeur d'application : Python - Openclassrooms</strong></h6>
               </div>
            </div>
         </div>
      </section>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'catalog/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'catalog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'catalog/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'catalog/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'catalog/js/creative.min.js' %}"></script>

</body>

</html>

pur_beurre/catalog/templates/catalog/credits.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block content %}

<header class="masthead text-center d-flex">
   <div class="container my-auto">
      <div class="row">
         <div class="col-lg-10 mx-auto pt-3 custom-color">
            <h4 class="text-uppercase">Mentions légales</h4>
             <hr class="divider my-4">
             <h5>Hébergé par : <a href="https://www.heroku.com/" target="_blank">Heroku</a></h5>
             <hr class="divider my-4">
             <h5>Template : <a href="https://blackrockdigital.github.io/startbootstrap-creative/" target="_blank">Bootstrap</a></h5>
             <hr class="divider my-4">
             <h5>Logo  <a href="https://company-82435.frontify.com/d/6Yy9WFJdtp8j/pur-beurre-style-guide#/elements-basiques/marque-et-logo" target="_blank">Pur-Beurre Openclassrooms</a></h5>
             <hr class="divider my-4">
             <h5>Icone  <a href="https://thenounproject.com/term/carrot/32551/" target="_blank">The Noun Project</a></h5>
             <hr class="divider my-4">
             <h5>Photo  <a href="https://unsplash.com/photos/eqsEZNCm4-c" target="_blank">Kawin Harasai</a></h5>
             <hr class="divider my-4">
             <h5>Portofolio  <a href="https://www.pixar.com/feature-films/ratatouille/#rat-main" target="_blank">Pixar Ratatouille</a></h5>
             <hr class="divider my-4">
         </div>
      </div>
   </div>
</header>

{% endblock %}

pur_beurre/catalog/templates/catalog/detail.html
{% extends "catalog/base.html" %}
{% block content %}
<header class="smallheader text-center text-white d-flex" style="background-image: url({{ product.picture }}) !important;">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>{{ product.name }}</strong>
                </h1>                
            </div>
        </div>
    </div>
</header>
<section id="detail">
<div class="container my-auto">
        <div class="row">
            <div id="detail" class="col-lg-12 text-center">

                <h2 class="section-heading">{{ title }}</h2>
                <hr class="my-4">
                <br>
                
                <img class="product-detail-img" src="https://static.openfoodfacts.org/images/misc/nutriscore-{{ product.nutrition_grade }}.svg" alt="nutrition score {{ product.nutrition_grade }}" title="Nutri-score {{ product.nutrition_grade }}" />
                <img class="product-detail-img" src="{{ product.nutrition_image }}" alt="nutrition 100g" title="Nutrition 100g" />
                <br>

                <a href="{{ product.url }}" class="btn btn-primary btn-xl mt-50" target="_blank">Voir la fiche Open Food Facts</a>
            </div>       
        </div>
</div>
</section>

{% endblock content %}

pur_beurre/catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load static %}

  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <h1 class="text-uppercase text-white font-weight-bold"><strong>DU GRAS, OUI, MAIS DE LA QUALITÉ !</strong></h1>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-8 align-self-baseline">
          <p class="text-white-75 font-weight-light mb-5"><strong>Trouvez un produit de subsitution pour ceux que vous consommez tous les jours</strong></p>
        
          <form id="search"  action="{% url 'catalog:search' %}" method="get" accept-charset="utf-8">
            <input type="text" name="query" id ="query" placeholder="Entrez le produit que vous voulez remplacer" required>
            <button type="submit" class="btn btn-primary btn-search">Chercher</button>
          </form>
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
    </div>
  </header>

  <!-- About Section -->
  <section id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">Colette et Rémy</h2>
            <hr class="divider my-4">
            <p class="text-muted mb-0"><strong>Nous sommes une jeune startup fondée par Remy et Colette Tatou, deux restaurateurs de renom. Notre restaurant, situé à Montmartre (Paris), compte une cinquantaine de couverts et ne désemplit pas. Notre spécialité, la ratatouille, nous attire une clientèle internationale charmée par les délices de ce plat typique.</strong></p>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-9 text-center">
            <div class="service-box mt-5 mx-auto">
              <img src="{% static 'catalog/img/colette.jpg' %}" title="Colette" alt="Colette" />
              <p class="text-muted mb-0 mt-2"><strong>Colette</strong></p>
            </div>
          </div>
          <div class="col-lg-6 col-md-9 text-center">
            <div class="service-box mt-5 mx-auto">
              <img src="{% static 'catalog/img/remy.jpg' %}" title="Rémy" alt="Rémy" />
              <p class="text-muted mb-0 mt-2"><strong>Rémy</strong></p>
            </div>
          </div>
    </section>



{% endblock %}

pur_beurre/catalog/templates/catalog/search.html
{% extends "catalog/base.html" %}
{% block content %}
<header class="smallheader text-center text-white d-flex" style="background-image: url({{ image }}) !important;">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>{{ title }}</strong>
                </h1>  
                {% if messages %}
                   {% for message in messages %}
                       <div class="alert alert-{{ message.tags }}">
                       {{ message }}
                       </div>
                   {% endfor %}
                {% endif %}              
            </div>
        </div>
    </div>
</header>
<section>
	<div class="container">
		<div class="col-md-18 text-center">    
		        <h2 class="section-heading">Vous pouvez remplacer cet aliment par :</h2>
		        <hr>
				{% for new_product in alt_products %}
					<div class="card product-card">
						<div class="product-card-badge">
                            <span class="product-nutrigrade badge badge-{{ new_product.nutrition_grade }}">{{ new_product.nutrition_grade }}</span>
                        </div>
						<div class="product-card-img" style="background-image: url({{ new_product.picture }})"></div>         
				            <div class="card-body">
				            <h4 class="card-title product-card-title">{{ new_product.name }}</h4>
							
							<a href="{% url 'catalog:detail' product_id=new_product.id %}"> détails</a>

							{% if user.is_authenticated %}
							<div class="save-result" id="{{ new_product.id }}"></div>
							<form method="post" action="{% url 'catalog:favorite' product_id=new_product.id%}">
							    {% csrf_token %}
							    <input class="btn btn-primary btn-xl mt-50" type="submit" value="Sauvegarder" id="{{ new_product.id }}">
							</form>
							{% endif %}
						</div>
					</div>
				{% endfor %}

				<div class="clearfix"></div>                
		</div>
	</div>	
</section>
{% endblock content %}

pur_beurre/users/templates/users/favorite.html
{% extends "catalog/base.html" %}
{% block content %}
<header class="smallheader text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Mes produits</strong>
                </h1>                
            </div>
        </div>
    </div>
</header>
<section id="favorite">
	<div class="container text-center my-auto">
		<div>
		    <h3>Liste de vos produits favoris</h3>
		    <hr> 
		        {% for product in favorite %}
		                <p><a href="{{ product.url }}">{{product.name}} - ({{ product.nutrition_grade }})</a></p>
		        {% endfor %}             
		</div>
	</div>
</section>
{% endblock content %}  

pur_beurre/users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}
<header class="smallheader text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Connexion</strong>
                </h1>                
            </div>
        </div>
    </div>
</header>
<section class="text-center d-flex">
    <div class="container my-auto">
        {% if error %}
        <p><strong>Utilisateur inconnu ou mauvais de mot de passe.</strong></p>
        {% endif %}

        {% if user.is_authenticated %}
        <h3>Vous êtes connecté, bienvenue {{ user.username }} !</h3>
        <br>
        <a href="{% url 'catalog:index' %}">Retourner à l'acceuil</a><br>
        <a href="{% url 'profile' %}">Mon compte</a>
        {% else %}
        <form method="post" action=".">
        {% csrf_token %}
            <fieldset class="form-group">
                <h3 class="border-bottom mb-3">Veuillez renseigner les champs ci-dessous:</h3>
            </fieldset>
            <div class="fieldWrapper my-label">
                <label for="{{ form.username.id_for_label }}">Nom d'utilisateur</label>
                {{ form.username }}
                {% if form.username.errors %}
                    {% for error in form.username.errors %}
                        <p class="errorform">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="fieldWrapper my-label">
                <label for="{{ form.password.id_for_label }}">Mot de passe</label>
                {{ form.password }}
                {% if form.password.errors %}
                    {% for error in form.password.errors %}
                        <p class="errorform">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <br>
            <div class="form-group">
                <button class="btn btn-primary btn-xl mt-50" type="submit">Se connecter</button>
            </div>
            <div>
                Nouvel utilisateur ? <a href="{% url 'register' %}">Créer mon compte</a>
            </div>
            <br>
            <div>
                Mot de passe oublié ? <a href="{% url 'password_reset' %}">Réinitialiser votre mot de passe</a>
            </div>
        </form>
        {% endif %}
    </div>
</section>

{% endblock content %}

pur_beurre/users/templates/users/logout.html
{% extends "catalog/base.html" %}
{% block content %}
<header class="smallheader text-center text-white d-flex">
</header>
<section class="text-center d-flex">
	<div class="container my-auto">
	    <h1>Vous êtes déconnecté</h1>
	    <div>
	            Possédez vous un compte ? <a href="{% url 'login' %}">connectez-vous</a>
	    </div>
	</div>
</section>

{% endblock content %}

pur_beurre/users/templates/users/password_change_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<header class="smallheader text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Modification du mot de passe</strong>
                </h1>
            </div>
        </div>
    </div>
</header>
<section class="text-center d-flex">
    <div class="container my-auto">

        <form method="post" action=".">
        {% csrf_token %}
            <fieldset class="form-group">
                <h3 class="border-bottom mb-3">Renseignez les champs ci-dessous:</h3>
            </fieldset>
            <div class="fieldWrapper my-label">
                <label for="id_old_password1">Ancien mot de passe</label>
                {{ form.old_password }}
                {% if form.old_password.errors %}
                    {% for error in form.old_password.errors %}
                        <p class="errorform">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="fieldWrapper my-label">
                <label for="id_new_password1">Nouveau mot de passe</label>
                {{ form.new_password1 }}
                {% if form.new_password1.errors %}
                    {% for error in form.new_password1.errors %}
                        <p class="errorform">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="fieldWrapper my-label">
                <label for="id_new_password2">Confirmation du mot de passe</label>
                {{ form.new_password2 }}
                {% if form.new_password2.errors %}
                    {% for error in form.new_password2.errors %}
                        <p class="errorform">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <br>
            <div class="form-group">
                <button class="btn btn-primary btn-xl mt-50" type="submit">Modifier</button>
            </div>
        </form>

    </div>
</section>

{% endblock content %}

pur_beurre/users/templates/users/password_reset_complete.html
{% extends "catalog/base.html" %}
{% block content %}
<header class="smallheader text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Récupération de votre mot de passe</strong>
                </h1>
            </div>
        </div>
    </div>
</header>
<section class="text-center d-flex"">
	<div class="container my-auto">
	    <h3>Votre mot de passe a bien été modifié!</h3><br>
        <div>
            <a href="{% url 'catalog:index' %}">Retourner à l'acceuil</a>
        </div>
        <br>
        <div>
            <a href="{% url 'login' %}">S'identifer</a>
         </div>
    </div>
</section>
{% endblock content %}

pur_beurre/users/templates/users/password_reset_confirm.html
{% extends 'catalog/base.html' %}
{% block content %}
<header class="smallheader text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Nouveau mot de passe</strong>
                </h1>
            </div>
        </div>
    </div>
</header>
<section class="text-center d-flex">
    <div class="container my-auto">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <h3 class="border-bottom mb-4">Renseigner les champs ci-dessous:</h3>

            <div class="fieldWrapper my-label">
                <label for="id_new_password1">Nouveau mot de passe : </label>
                {{ form.new_password1 }}
            </div>

            <div class="fieldWrapper my-label">
                <label for="id_new_password2">Confirmation du nouveau mot de passe :</label>
                {{ form.new_password2 }}
            </div>

            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary btn-xl mt-50" type="submit">Confirmer</button>
            </div>
        </form>
    </div>
</section>
{% endblock content %}

pur_beurre/users/templates/users/password_reset_done.html
{% extends 'catalog/base.html' %}
{% block content %}
<header class="smallheader text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Récupération de votre mot de passe</strong>
                </h1>
            </div>
        </div>
    </div>
</header>
<section class="text-center d-flex">
    <div class="container my-auto">
        <h3>Un email avec les étapes à suivre vient de vous être envoyé.</h3>
    </div>
</section>

{% endblock content %}